USE DIPE;

DELIMITER $$


DROP TRIGGER IF EXISTS AUTO_DROP_FIELDS_AND_CONSTRAINT_BEFORE_DROPPING_TABLE $$
CREATE TRIGGER AUTO_DROP_FIELDS_AND_CONSTRAINT_BEFORE_DROPPING_TABLE
BEFORE DELETE ON `tables`
FOR EACH ROW
BEGIN
	DELETE FROM `constraints` WHERE field_id IN ( SELECT field_id FROM `fields` WHERE table_id = OLD.table_id );
    DELETE FROM `default_value` WHERE field_id IN ( SELECT field_id FROM `fields` WHERE table_id = OLD.table_id );
    DELETE FROM `fields` WHERE table_id = OLD.table_id;
END
$$

DROP TRIGGER IF EXISTS AUTO_DROP_DEFAULT_VALUE_BEFORE_DROPPING_FIELD $$
CREATE TRIGGER AUTO_DROP_DEFAULT_VALUE_BEFORE_DROPPING_FIELD
BEFORE DELETE ON `fields`
FOR EACH ROW
BEGIN
    DELETE FROM `default_value` WHERE field_id = OLD.field_id;
END
$$


DROP TRIGGER IF EXISTS DROP_ACCOUNT_DETAIL_BEFORE_DROPING_ACCOUNT $$
CREATE TRIGGER DROP_ACCOUNT_DETAIL_BEFORE_DROPING_ACCOUNT
BEFORE DELETE ON `accounts` 
FOR EACH ROW
BEGIN
	DELETE FROM `account_detail` WHERE credential_string = OLD.credential_string;
    DELETE FROM `projects` WHERE project_master = OLD.credential_string;
    DELETE FROM `project_partner` WHERE credential_string = OLD.credential_string;
    DELETE FROM `project_user` WHERE credential_string = OLD.credential_string;
END

$$

DROP TRIGGER IF EXISTS AUTOMATED_ADD_TASK_TO_PROJECT_TASK_AFTER_CREATED_ONE $$
CREATE TRIGGER AUTOMATED_ADD_TASK_TO_PROJECT_TASK_AFTER_CREATED_ONE 
AFTER INSERT ON PROJECTS 
FOR EACH ROW
BEGIN
	INSERT INTO TASKS(PROJECT_ID, TASK_OWNER, TASK_LABEL, TASK_STATE) VALUES ( NEW.PROJECT_ID, NEW.PROJECT_MASTER, "INITIALIZED PROJECT FOR THE BEGINNING",4 );
    INSERT INTO VERSIONS (version_name, project_id, publisher, descriptions) VALUES ( "V0.0.1", NEW.PROJECT_ID, NEW.PROJECT_MASTER, "Version tươi mới như mối tình đầu" );
END
$$
